### ISSUE TITLE
테이블 구조 및 서비스 설계

### ISSUE THREAD

**Issue by nayu1105** [nayu1105/NotionManagement#1]
<요구사항>
페이지 정보 조회 API : 특정 페이지의 정보를 조회할 수 있는 API 구현
- 각 페이지는 제목, 컨텐츠, 서브 페이지를 가질 수 있다.
- 특정 페이지에 대한 브로드 크럼스(Breadcrumbs) 정보도 반환해야 한다.

- 입력 : 페이지 ID
- 출력 : 페이지 제목, 컨텐츠, 서브 페이지 리스트, 브로드 크럼스 (페이지 1> 페이지 3> 페이지 5)

위 요구사항에 맞는 테이블 구조 및 서비스 설계를 어떻게 하면 좋을까요?

**Comment by moseoh** [comment]
# Notion Api

## Page Table

### Table

| `Name`    | `Type`             | `Nullable` |
|-----------|--------------------|------------|
| id        | int auto_increment | `No`       |
| title     | varchar(50)        | `No`       |
| context   | text               | `No`       |
| parent_id | int                | `Yes`      |

### Entity

```java
class Page {
    private long id;
    private String title;
    private String context;
    private Page parent;
    private List<Page> subPages;
}
```

## Page DTO

### `breadcrumbs`

`breadcrumbs` 는 `페이지 1 > 페이지 3 > 페이지 5` 같은 예시가 나와있지만\
해당 정보를 제공하는 목적은 페이지 네비게이션 표기와 '이동'이 목적이기 때문에 `id` 정보를 포함하여 제공해야 한다고 생각합니다.\
또한 프론트 개발자와의 협업 경험 중 계층 구조로 보내도 좋다고 한 기억이 있어 평소 생각한 구조는 아래와 같습니다.

```java
class PageDetails {
    private long id;
    private String title;
    private String context;
    private List<Sub> subPages;
    private BreadCrumb parent;

    class BreadCrumb {
        private long id;
        private String title;
        private PageBreadCrumb parent;
    }

    class Sub {
        private long id;
        private String title;
    }
}


```

```json
{
  "id": 1,
  "title": "page",
  "context": "context",
  "subPages": [
    {
      "id": 2,
      "title": "page2"
    },
    {
      "id": 3,
      "title": "page3"
    }
  ],
  "parent": {
    "id": 4,
    "title": "page4",
    "parent": {
      "id": 5,
      "title": "page5",
      "parent": null
    }
  }
}
```

위의 구조 이외 제시된 예제 및 json-ld를 활용한 breadcrumbs 구조는 아래와 같습니다.

예제:

```json
{
  "pageId": 1,
  "title": 1,
  "subPages": [],
  "breadcrumbs": [
    "A",
    "B",
    "C"
  ]
  // 혹은 "breadcrumbs" : "A / B / C"
}
```

구글 참조:\
https://developers.google.com/search/docs/appearance/structured-data/breadcrumb?hl=ko

```json
    [
  {
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    "itemListElement": [
      {
        "@type": "ListItem",
        "position": 1,
        "name": "Books",
        "item": "https://example.com/books"
      },
      {
        "@type": "ListItem",
        "position": 2,
        "name": "Science Fiction",
        "item": "https://example.com/books/sciencefiction"
      },
      {
        "@type": "ListItem",
        "position": 3,
        "name": "Award Winners"
      }
    ]
  },
  {
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    "itemListElement": [
      {
        "@type": "ListItem",
        "position": 1,
        "name": "Literature",
        "item": "https://example.com/literature"
      },
      {
        "@type": "ListItem",
        "position": 2,
        "name": "Award Winners"
      }
    ]
  }
]
```

### 결과

계층 구조

- 관계의 시각화가 가능하다.
- 재귀에 따른 문제가 발생할 수 있다.
- 데이터 처리가 복잡할 수 있다.

Flat한 구조

- 데이터 처리가 간단하다.
- 관계를 시각적으로 파악하기 어려울 수 있다.

기술 선정이나 설계시 장단점을 뚜렷이 확인할 수 없는 경우, 협업자와 함께 상의하거나 다른 플랫폼을 따르곤 합니다.\
여기선 구글의 예제를 따라 Flat한 구조로 작성하려고 합니다.

```java
class PageDetails {
    private long id;
    private String title;
    private String context;
    private List<PageSummary> breadcrumbs;
    private List<PageSummary> subPages;
}

class PageSummary {
    private long id;
    private String title;
}
```

```json
{
  "id": 1,
  "title": "page",
  "context": "context",
  "breadcrumbs": [
    {
      "id": 2,
      "title": "page2"
    },
    {
      "id": 3,
      "title": "page3"
    }
  ],
  "subPages": [
    {
      "id": 4,
      "title": "page4"
    }
  ]
}
```

## Mapper 및 Service

DTO에 알맞은 데이터를 반환할 수 있도록 작성

## Controller

`{host}/page/{id}` 으로 url get method 작성

**Comment by kim-ksp7331** [comment]
# NOTION API
## 테이블
### db diagram
![Untitled (7)](https://github.com/nayu1105/NotionManagement/assets/119999208/ff5cce4c-322c-4bdc-b195-b255ffd0b44f)
### 스키마
```sql
CREATE TABLE IF NOT EXISTS POST (
    ID bigint NOT NULL AUTO_INCREMENT,
    TITLE VARCHAR(30) NOT NULL,
    CONTENT TEXT NOT NULL,
    PARENT_ID bigint,
    PRIMARY KEY (ID),
    FOREIGN KEY (PARENT_ID) REFERENCES POST(ID)
);
```
페이지와 페이지를 연결하기 위해 자가 참조를 하도록 설계했습니다.
## DTO
```java
public class PostDTO {

    @Getter
    @AllArgsConstructor
    @Builder
    public static class Response {
        private Long id;
        private String title;
        private String content;
        private List<Page> subPages;
        private List<Page> breadcrumbs;

        static class Page {
            private Long id;
            private String title;
        }
    }
}
```
subPages에는 하위 페이지들을 반환하도록 하고, breadcrumbs에는 상위 페이지들을 반환하도록 했습니다.
/post/{post-id}로 요청이 들어 올 경우, db로부터 해당 id를 가지는 포스트와 그 하위 포스트들, 해당 포스트의 상위 포스트의 정보를 반환합니다.

**Comment by nayu1105** [comment]
## Table
<html>
<body>


Name | Type | Nullable | default
-- | -- | -- | --
id | bigint auto_increment | no |  
title | varchar(100) | no |  
content | varchar(1000) | no | ‘’
reg_dt | datetime | no | CURRENT_TIMESTAMP
parents_id | bigint | yes |  



</body>
</html>

## Post Dto

```java
class Post {
	private Long id;
	private String title;
	private String content;
	private reg_dt Date;
	private BreadCrumb parents;
	private List<SubPost> subPosts;

	class BreadCrumb {
		private Long id;
		private String title;
		private BreadCrumb parent;
	}
	
	class SubPost{
		private Long id;
		private String title;
	}
}
```

## Sub Post 서비스

- parent_id == id 조건 쿼리로, 현재 페이지를 부모로 하는 페이지들 셀렉트


## BreadCrumb 서비스

1. 서비스 단에서 parents 아이디로 재귀 호출
2. 재귀 쿼리를 활용하여 1번 호출 후, 클래스 구조에 맞게 수정

1번이 구현은 쉬우나, DB 접근이 많아 시간 소요가 클듯.

2번이 쿼리 문 작성과 클래스 구조에 맞게 변경은 어려우나 속도는 빠를 듯.

## 결론

DB 접근이 많은 것보다 재귀 SQL 을 활용하는 방법이 좋을 듯 하다.

예상 쿼리문
```
with recursive cte (id, title, parent_id) as (
 select     id,
            title,
            parent_id
 from       post
 where      id = 9
 union all
 select     r.id,
            r.title,
            r.parent_id
 from       post r
 inner join cte
         on r.id = cte.parent_id
) select * from cte;

```
